// Define all your images manually in an array
export const cardBackgrounds = [
    require('../assets/card_image/1.jpeg'),
    require('../assets/card_image/2.jpeg'),
    require('../assets/card_image/3.jpeg'),
    require('../assets/card_image/4.jpeg'),
    require('../assets/card_image/5.jpeg'),
    require('../assets/card_image/6.jpeg'),
    require('../assets/card_image/7.jpeg'),
    require('../assets/card_image/8.jpeg'),
    require('../assets/card_image/9.jpeg'),
    require('../assets/card_image/10.jpeg'),
    require('../assets/card_image/11.jpeg'),
    require('../assets/card_image/12.jpeg'),
    require('../assets/card_image/13.jpeg'),
    require('../assets/card_image/14.jpeg'),
    require('../assets/card_image/15.jpeg'),
    require('../assets/card_image/16.jpeg'),
    require('../assets/card_image/17.jpeg'),
    require('../assets/card_image/18.jpeg'),
    require('../assets/card_image/19.jpeg'),
    require('../assets/card_image/20.jpeg'),
    require('../assets/card_image/21.jpeg'),
    require('../assets/card_image/22.jpeg'),
    require('../assets/card_image/23.jpeg'),
    require('../assets/card_image/24.jpeg'),
    require('../assets/card_image/25.jpeg'),
];